### ISSUE TITLE
Mismatch in copyright statements

### ISSUE THREAD

**Issue by kgroat** [sqreen/twofa#3]
In the LICENSE file, you're using an MIT license, which states:
> Permission is hereby granted, free of charge, to any person obtaining a copy
> of this software and associated documentation files (the "Software"), to deal
> in the Software without restriction, including without limitation the rights
> to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
> copies of the Software, and to permit persons to whom the Software is
> furnished to do so, subject to the following conditions: [...]

However, in your Info.plist, the copyright reads:
> Copyright © 2019 Sqreen Inc. All rights reserved.

These two statements are in conflict.  Either the rights are reserved or they are granted without restriction.  If the software is truly licensed under the MIT license, the copyright in your Info.plist should read something like:
> Copyright © 2019 Sqreen Inc. Licensed under MIT.

**Comment by sfc-gh-afedorov** [comment]
Pretty sure this means all rights that are not explicitly granted by the license are reserved to the fullest extent of the law within your jurisdiction.

(not a lawyer)

**Comment by jkirsteins** [comment]
Affirming that the licence is indeed MIT.

I agree it might be redundant, but I don't see any issue with this. See: https://opensource.stackexchange.com/questions/2121/mit-license-and-all-rights-reserved
